#include <stdint.h>
const uint32_t cost_table[128] = {
    0,	// NULL	(Null character)
    0,	// SOH	(Start of Header)
    0,	// STX	(Start of Text)
    0,	// ETX	(End of Text)
    0,	// EOT	(End of Transmission)
    0,	// ENQ	(Enquiry)
    0,	// ACK	(Acknowledgement)
    0,	// BEL	(Bell)
    0,	// BS	(Backspace)
    0,	// HT	(Horizontal Tab)
    0,	// LF	(Line feed)
    0,	// VT	(Vertical Tab)
    0,	// FF	(Form feed)
    0,	// CR	(Carriage return)
    0,	// SO	(Shift Out)
    0,	// SI	(Shift In)
    0,	// DLE	(Data link escape)
    0,	// DC1	(Device control 1)
    0,	// DC2	(Device control 2)
    0,	// DC3	(Device control 3)
    0,	// DC4	(Device control 4)
    0,	// NAK	(Negative acknowledgement)
    0,	// SYN	(Synchronous idle)
    0,	// ETB	(End of transmission block)
    0,	// CAN	(Cancel)
    0,	// EM	(End of medium)
    0,	// SUB	(Substitute)
    0,	// ESC	(Escape)
    0,	// FS	(File separator)
    0,	// GS	(Group separator)
    0,	// RS	(Record separator)
    0,	// US	(Unit separator)
    4,	//  	(space)
    0,	// !	(exclamation mark)
    0,	// "	(Quotation mark)
    1,	// #	(Number sign)
    0,	// $	(Dollar sign)
    0,	// %	(Percent sign)
    0,	// &	(Ampersand)
    0,	// '	(Apostrophe)
    0,	// (	(round brackets or parentheses)
    0,	// )	(round brackets or parentheses)
    0,	// *	(Asterisk)
    0,	// +	(Plus sign)
    0,	// ,	(Comma)
    0xDEADBEEF,	// -	(Hyphen)
    0, // .	(Full stop , dot)
    0, // /	(Slash)
    0, // 0	(number zero)
    0, // 1	(number one)
    0, // 2	(number two)
    0, // 3	(number three)
    0, // 4	(number four)
    0, // 5	(number five)
    0, // 6	(number six)
    0, // 7	(number seven)
    0, // 8	(number eight)
    0, // 9	(number nine)
    0, // :	(Colon)
    0, // ;	(Semicolon)
    0, // <	(Less-than sign )
    0, // =	(Equals sign)
    0, // >	(Greater-than sign ; Inequality)
    0, // ?	(Question mark)
    0xDEADBEEF, // @	(At sign)
    0, // A	(Capital A )
    0, // B	(Capital B )
    0, // C	(Capital C )
    0, // D	(Capital D )
    0, // E	(Capital E )
    0, // F	(Capital F )
    0, // G	(Capital G )
    0, // H	(Capital H )
    0, // I	(Capital I )
    0, // J	(Capital J )
    0, // K	(Capital K )
    0, // L	(Capital L )
    0, // M	(Capital M )
    0, // N	(Capital N )
    0, // O	(Capital O )
    0, // P	(Capital P )
    0, // Q	(Capital Q )
    0, // R	(Capital R )
    0, // S	(Capital S )
    0, // T	(Capital T )
    0, // U	(Capital U )
    0, // V	(Capital V )
    0, // W	(Capital W )
    0, // X	(Capital X )
    0, // Y	(Capital Y )
    0, // Z	(Capital Z )
    0, // [	(square brackets or box brackets)
    0, // \	(Backslash)
    0, // ]	(square brackets or box brackets)
    0, // ^	(Caret or circumflex accent)
    0, // _	(underscore , understrike , underbar or low line)
    0, // `	(Grave accent)
    0, // a	(Lowercase  a )
    0, // b	(Lowercase  b )
    0, // c	(Lowercase  c )
    0, // d	(Lowercase  d )
    0, // e	(Lowercase  e )
    0, // f	(Lowercase  f )
    0, // g	(Lowercase  g )
    0, // h	(Lowercase  h )
    0, // i	(Lowercase  i )
    0, // j	(Lowercase  j )
    0, // k	(Lowercase  k )
    0, // l	(Lowercase  l )
    0, // m	(Lowercase  m )
    0, // n	(Lowercase  n )
    0, // o	(Lowercase  o )
    0, // p	(Lowercase  p )
    0, // q	(Lowercase  q )
    0, // r	(Lowercase  r )
    0, // s	(Lowercase  s )
    0, // t	(Lowercase  t )
    0, // u	(Lowercase  u )
    0, // v	(Lowercase  v )
    0, // w	(Lowercase  w )
    0, // x	(Lowercase  x )
    0, // y	(Lowercase  y )
    0, // z	(Lowercase  z )
    0, // {	(curly brackets or braces)
    0xDEADBEEF, // |	(vertical-bar, vbar, vertical line or vertical slash)
    0, // }	(curly brackets or braces)
    0, // ~	(Tilde ; swung dash)
    0, // DEL	(Delete)
};
